FROM public.ecr.aws/lambda/python:3.8-x86_64

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN  pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY .env ${LAMBDA_TASK_ROOT}
COPY sql_wrapper.py ${LAMBDA_TASK_ROOT}
COPY main.py ${LAMBDA_TASK_ROOT}

CMD ["main.lambda_handler"]